export interface FusionWeightPresentation {
  text: number;
  audio: number;
  phq: number;
}

export const ASSESSMENT_REPORT_TITLE = 'Assessment Report';
export const ASSESSMENT_REPORT_HEADING = 'MindScreen Mental Health Screening Summary';
export const ASSESSMENT_REPORT_STATUS = 'Research Prototype — Not Clinically Validated';
export const ASSESSMENT_REPORT_DISCLAIMER =
  'This assessment is generated by a research prototype and is not a clinical diagnosis, medical assessment, or substitute for evaluation by a qualified mental-health professional.';

export function createResultsNavigationState<T>(result: T, phqAnswers: number[]) {
  return { result, phqAnswers: [...phqAnswers] };
}

export function calculatePhqTotal(phqAnswers?: number[]): number | null {
  return phqAnswers ? phqAnswers.reduce((total, answer) => total + answer, 0) : null;
}

export function formatPercentage(value: number): string {
  return `${value.toFixed(1)}%`;
}

export function formatPriorityScore(value: number): string {
  return formatPercentage(value * 100);
}

export function getAudioUsageSummary(audioPresent: boolean): string {
  return audioPresent
    ? 'Based on your PHQ-9 responses, text analysis, and acoustic recording'
    : 'Based on your PHQ-9 responses and text analysis; audio was not used';
}

export function getEffectiveFusionWeights(audioPresent: boolean): FusionWeightPresentation {
  if (audioPresent) {
    return { text: 50, audio: 30, phq: 20 };
  }
  return { text: (5 / 7) * 100, audio: 0, phq: (2 / 7) * 100 };
}

export function getCrisisAttribution(phqAnswers?: number[], crisisTrigger?: string | null): string {
  const item9Endorsed = Boolean(phqAnswers && phqAnswers[8] > 0);
  const textCrisisDetected = Boolean(crisisTrigger);

  if (item9Endorsed && textCrisisDetected) {
    return 'Reasons: PHQ-9 Item 9 was endorsed and affirmative crisis language was detected in the text entry.';
  }
  if (item9Endorsed) {
    return 'Reason: PHQ-9 Item 9 was endorsed.';
  }
  if (textCrisisDetected) {
    return 'Reason: Affirmative crisis language was detected in the text entry.';
  }
  return 'Reason: An explicit crisis signal was recorded; its source is unavailable in this result.';
}
